/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103x6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "Stm32_F103C6_USART_driver.h"
#include "lcd_driver.h"
#include "keypad_driver.h"


void clock_init()
{
	// TO ENABLE CLOCK SIGNAL FOR GPIOA
	RCC_GPIOA_CLK_EN();
	// TO ENABLE CLOCK SIGNAL FOR GPIOB
	RCC_GPIOB_CLK_EN();

	RCC_AFIO_CLK_EN();
}

unsigned char ch;

void UART_IRQ_Callback(void)
{
	MCAL_UART_ReceiveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);
}

int main(void)
{
	UART_Config UART_Config;
	clock_init();
	UART_Config.BaudRate= UART_BaudRate_115200;
	UART_Config.FlowCtl=UART_FlowCtl_NONE;
	UART_Config.IRQ_Enable=UART_IRQ_Enable_RXNIE;
	UART_Config.P_IRQ_CallBack = UART_IRQ_Callback;
	UART_Config.Parity=UART_Parity_NONE;
	UART_Config.payload_Length=UART_payloadLength_8B;
	UART_Config.StopBits=UART_StopBits_1;
	UART_Config.USART_Mode=UART_Mode_TX_Rx;

	MCAL_UART_Init(USART1, &UART_Config);
	MCAL_UART_SetPins(USART1);
	while(1)
	{

	}
}
