/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103x6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"



void clock_init()
{
	// TO ENABLE CLOCK SIGNAL FOR GPIOA
	RCC_GPIOA_CLK_EN();
	// TO ENABLE CLOCK SIGNAL FOR GPIOB
	RCC_GPIOB_CLK_EN();

}
void GPIO_init()
{

	//PA1 input HighZ
	GPIO_PConfig_t PinConfig;
	PinConfig.GPIO_PinNumber=GPIO_PIN_1;
	PinConfig.GPIO_MODE= GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinConfig);

	//PA13 input HighZ
	PinConfig.GPIO_PinNumber=GPIO_PIN_13;
	PinConfig.GPIO_MODE= GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinConfig);

	//PB1 output push pull mode
	PinConfig.GPIO_PinNumber=GPIO_PIN_1;
	PinConfig.GPIO_MODE= GPIO_MODE_OUTPUT_PP;
	PinConfig.GPIO_Output_SPeed=GPIO_OutputSpeed_10M;
	MCAL_GPIO_Init(GPIOB, &PinConfig);

	//PB13 output push pull mode
	PinConfig.GPIO_PinNumber=GPIO_PIN_13;
	PinConfig.GPIO_MODE= GPIO_MODE_OUTPUT_PP;
	PinConfig.GPIO_Output_SPeed=GPIO_OutputSpeed_10M;
	MCAL_GPIO_Init(GPIOB, &PinConfig);

}

void wait(int x)
{
	unsigned int i , j;
	for(i=0 ; i<x ; i++)
		for(j=0 ; j<255 ; j++);
}

int main(void)
{
	clock_init();
	GPIO_init();



	while(1)
	{
		//PA1 > connected to external PUR
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0 ) //press
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0 ); //Single press
		}

		//PA13 > connected to external PDR
		if( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1) // Multi pressing
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);

		}

		wait(1);
	}

}
