/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#define MCU_Act_As_Master
//#define MCU_Act_As_Slave

#include "Stm32_F103x6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "Stm32_F103C6_USART_driver.h"
#include "lcd_driver.h"
#include "keypad_driver.h"
#include "Stm32_F103C6_SPI_driver.h"


void clock_init()
{
	// TO ENABLE CLOCK SIGNAL FOR GPIOA
	RCC_GPIOA_CLK_EN();
	// TO ENABLE CLOCK SIGNAL FOR GPIOB
	RCC_GPIOB_CLK_EN();

	RCC_AFIO_CLK_EN();
}

unsigned char ch;

void UART_IRQ_Callback(void)
{
#ifdef MCU_Act_As_Master

	MCAL_UART_ReceiveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);
	//Send to SPI
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 0);
	MCAL_SPI_TX_RX(SPI1, &ch, PollingEnable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);

#endif

}

int main(void)
{
	UART_Config UART_Config;

	clock_init();
	UART_Config.BaudRate= UART_BaudRate_115200;
	UART_Config.FlowCtl=UART_FlowCtl_NONE;
	UART_Config.IRQ_Enable=UART_IRQ_Enable_RXNIE;
	UART_Config.P_IRQ_CallBack = UART_IRQ_Callback;
	UART_Config.Parity=UART_Parity_NONE;
	UART_Config.payload_Length=UART_payloadLength_8B;
	UART_Config.StopBits=UART_StopBits_1;
	UART_Config.USART_Mode=UART_Mode_TX_Rx;

	MCAL_UART_Init(USART1, &UART_Config);
	MCAL_UART_SetPins(USART1);

	SPI_Config SPI_Config;
	SPI_Config.ClkPhase=SPI_ClkPhase_Second_Edge;
	SPI_Config.ClkPolarity=SPI_ClkPolarity_HighIDLE;
	SPI_Config.DataSize=SPI_DataSize_8Bit;
	SPI_Config.FrameFormat=SPI_FrameFormat_MSB_First;
	SPI_Config.SPI_Prescaler = SPI_Prescaler_8;            //assume by default pclk2 = 8MHZ
	SPI_Config.Communication_Mode=SPI_CommunicationMode_2Line_TX_RX;

#ifdef MCU_Act_As_Master

	SPI_Config.SPI_Mode=SPI_Mode_Master;
	SPI_Config.IRQ_Enable=SPI_IRQ_Enable_NONE;
	SPI_Config.NSS=SPI_NSS_SW_Internal_slave_select;
	SPI_Config.P_IRQ_CallBack=NULL;

#endif

	MCAL_SPI_Init(SPI1, &SPI_Config);
	MCAL_SPI_GPIO_SetPins(SPI1);

	//Configure Slave select on PA.4 by GPIO
	GPIO_PConfig_t PinCfg;
	PinCfg.GPIO_PinNumber = GPIO_PIN_4;
	PinCfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_SPeed=GPIO_OutputSpeed_10M;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);

	while(1)
	{

	}
}
